import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Barras laterais da instância "squad": cada uma vira uma aba na navbar.
const sidebars: SidebarsConfig = {
  processos: [{type: 'autogenerated', dirName: 'processos'}],
  ia: [{type: 'autogenerated', dirName: 'uso-de-ia'}],
};

export default sidebars;
